
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `filmotheque` (
  `idfilmotheque` int(11) NOT NULL AUTO_INCREMENT,
  `brutname` varchar(255) DEFAULT NULL,
  `pathname` varchar(255) DEFAULT NULL,
  `filename` varchar(255) DEFAULT NULL,
  `purename` varchar(255) DEFAULT NULL,
  `customename` varchar(255) DEFAULT NULL,
  `clearname` varchar(255) DEFAULT NULL,
  `videocodec` varchar(255) DEFAULT NULL,
  `audiocodec` varchar(255) DEFAULT NULL,
  `definition` varchar(255) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `contenair` varchar(255) DEFAULT NULL,
  `adddate` datetime DEFAULT NULL,
  `verifydate` datetime DEFAULT NULL,
  `md5sum` varchar(255) DEFAULT NULL,
  `deleted` varchar(255) DEFAULT NULL,
  `grade` int(11) DEFAULT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `saw` int(11) DEFAULT NULL,
  `allocinecode` int(11) DEFAULT NULL,
  PRIMARY KEY (`idfilmotheque`)
) ENGINE=MyISAM AUTO_INCREMENT=965 DEFAULT CHARSET=latin1 COMMENT='Informations filmotheque';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

